import { Called, Message } from "./mensagem.model";

export const MESSAGE_EXEMPLOS_1: Message[] = [
  {
    body: null,
    date: "2024-05-07T12:35:16.000Z",
    caption: "",
    type: "image",
    sent: false,
    user: null,
  },
  {
    body: "Mas ainda tenho problemas com alguns clientes que não aparecem nas mensagens",
    date: "2024-05-07T12:34:05.000Z",
    caption: null,
    type: "chat",
    sent: false,
    user: null,
  },
  {
    body: "Voltaram a funcionar",
    date: "2024-05-07T12:33:47.000Z",
    caption: null,
    type: "chat",
    sent: false,
    user: null,
  },
  {
    body: "Oi",
    date: "2024-05-07T12:33:40.000Z",
    caption: null,
    type: "chat",
    sent: false,
    user: null,
  },
  {
    body: "🙎‍♂️ *Michael Mascarenhas:*\nEi Francielli, bom dia!\n\nEstou passando para verificar como vai indo o uso do HUST CHAT, e se os orçamentos estão configurados da forma que solicitou?",
    date: "2024-05-07T12:24:52.000Z",
    caption: null,
    type: "chat",
    sent: true,
    user: {
      nome: "Michael Mascarenhas",
      id_user: 5031,
      foto_perfil: "l18NKYEZl0K6PF04RzngsVLUKvxxgAS4QkzjbHD2K8ug087puJ.png",
    },
  },
  {
    body: "🙎‍♂️ *Michael Mascarenhas:*\nme passa seu anydesk por favor",
    date: "2024-04-29T15:08:08.000Z",
    caption: null,
    type: "chat",
    sent: true,
    user: {
      nome: "Michael Mascarenhas",
      id_user: 5031,
      foto_perfil: "l18NKYEZl0K6PF04RzngsVLUKvxxgAS4QkzjbHD2K8ug087puJ.png",
    },
  },
  {
    body: "Porem o # parou",
    date: "2024-04-29T15:06:58.000Z",
    caption: null,
    type: "chat",
    sent: false,
    user: null,
  },
  {
    body: "Agora voltou as mensagens",
    date: "2024-04-29T15:06:51.000Z",
    caption: null,
    type: "chat",
    sent: false,
    user: null,
  },
  {
    body: "🙎‍♂️ *Michael Mascarenhas:*\nFrancielli, verifiquei as configurações de você e não encontrei inconsistências. \n\nFiz o reinicio da conexão whatsapp de vocês. \n\npoderia detalhar um pouco sobre o problema que estão tendo e se ainda persiste?",
    date: "2024-04-29T13:58:16.000Z",
    caption: null,
    type: "chat",
    sent: true,
    user: {
      nome: "Michael Mascarenhas",
      id_user: 5031,
      foto_perfil: "l18NKYEZl0K6PF04RzngsVLUKvxxgAS4QkzjbHD2K8ug087puJ.png",
    },
  },
  {
    body: "Permanece o problema",
    date: "2024-04-29T13:44:35.000Z",
    caption: null,
    type: "chat",
    sent: false,
    user: null,
  },
  {
    body: "Nao esta funcionando",
    date: "2024-04-29T13:44:26.000Z",
    caption: null,
    type: "chat",
    sent: false,
    user: null,
  },
  {
    body: "🙎‍♂️ *Michael Mascarenhas:*\nEi, Bom dia!\n\nTivemos uma breve indisponibilidade, porém, acabou de ser resolvido. \n\npoderia verificar se está OK para vocês?",
    date: "2024-04-29T13:17:34.000Z",
    caption: null,
    type: "chat",
    sent: true,
    user: {
      nome: "Michael Mascarenhas",
      id_user: 5031,
      foto_perfil: "l18NKYEZl0K6PF04RzngsVLUKvxxgAS4QkzjbHD2K8ug087puJ.png",
    },
  },
  {
    body: "As mensagens não estão indo",
    date: "2024-04-29T12:32:07.000Z",
    caption: null,
    type: "chat",
    sent: false,
    user: null,
  },
  {
    body: "Chat caiu de novo",
    date: "2024-04-29T12:31:53.000Z",
    caption: null,
    type: "chat",
    sent: false,
    user: null,
  },
  {
    body: "Ola",
    date: "2024-04-29T12:31:48.000Z",
    caption: null,
    type: "chat",
    sent: false,
    user: null,
  },
  {
    body: "E os atendimentos daqueles clientes que citei ainda não corrigiu",
    date: "2024-04-22T16:20:36.000Z",
    caption: null,
    type: "chat",
    sent: false,
    user: null,
  },
  {
    body: "Parou de sair a descrição",
    date: "2024-04-22T16:20:05.000Z",
    caption: null,
    type: "chat",
    sent: false,
    user: null,
  },
  {
    body: "Ainda não resolveu",
    date: "2024-04-22T16:19:56.000Z",
    caption: null,
    type: "chat",
    sent: false,
    user: null,
  },
  {
    body: "Aguardo",
    date: "2024-04-22T11:50:57.000Z",
    caption: null,
    type: "chat",
    sent: false,
    user: null,
  },
  {
    body: "Ei Francielli, já vou verificar o que aconteceu, só um momento por favor.",
    date: "2024-04-22T11:50:06.000Z",
    caption: null,
    type: "chat",
    sent: true,
    user: {
      nome: "Michael Mascarenhas",
      id_user: 5031,
      foto_perfil: "l18NKYEZl0K6PF04RzngsVLUKvxxgAS4QkzjbHD2K8ug087puJ.png",
    },
  },
];

export const MESSAGE_EXEMPLOS_2: Message[] = [
  {
    body: null,
    date: "2024-05-07T12:35:16.000Z",
    caption: "",
    type: "image",
    sent: false,
    user: null,
  },
  {
    body: "Mas ainda tenho problemas com alguns clientes que não aparecem nas mensagens",
    date: "2024-05-07T12:34:05.000Z",
    caption: null,
    type: "chat",
    sent: false,
    user: null,
  },
  {
    body: "Voltaram a funcionar",
    date: "2024-05-07T12:33:47.000Z",
    caption: null,
    type: "chat",
    sent: false,
    user: null,
  },
  {
    body: "Oi",
    date: "2024-05-07T12:33:40.000Z",
    caption: null,
    type: "chat",
    sent: false,
    user: null,
  },
  {
    body: "🙎‍♂️ *Michael Mascarenhas:*\nEi Francielli, bom dia!\n\nEstou passando para verificar como vai indo o uso do HUST CHAT, e se os orçamentos estão configurados da forma que solicitou?",
    date: "2024-05-07T12:24:52.000Z",
    caption: null,
    type: "chat",
    sent: true,
    user: {
      nome: "Michael Mascarenhas",
      id_user: 5031,
      foto_perfil: "l18NKYEZl0K6PF04RzngsVLUKvxxgAS4QkzjbHD2K8ug087puJ.png",
    },
  },
  {
    body: "🙎‍♂️ *Michael Mascarenhas:*\nme passa seu anydesk por favor",
    date: "2024-04-29T15:08:08.000Z",
    caption: null,
    type: "chat",
    sent: true,
    user: {
      nome: "Michael Mascarenhas",
      id_user: 5031,
      foto_perfil: "l18NKYEZl0K6PF04RzngsVLUKvxxgAS4QkzjbHD2K8ug087puJ.png",
    },
  },
  {
    body: "Porem o # parou",
    date: "2024-04-29T15:06:58.000Z",
    caption: null,
    type: "chat",
    sent: false,
    user: null,
  },
  {
    body: "Agora voltou as mensagens",
    date: "2024-04-29T15:06:51.000Z",
    caption: null,
    type: "chat",
    sent: false,
    user: null,
  },
  {
    body: "🙎‍♂️ *Michael Mascarenhas:*\nFrancielli, verifiquei as configurações de você e não encontrei inconsistências. \n\nFiz o reinicio da conexão whatsapp de vocês. \n\npoderia detalhar um pouco sobre o problema que estão tendo e se ainda persiste?",
    date: "2024-04-29T13:58:16.000Z",
    caption: null,
    type: "chat",
    sent: true,
    user: {
      nome: "Michael Mascarenhas",
      id_user: 5031,
      foto_perfil: "l18NKYEZl0K6PF04RzngsVLUKvxxgAS4QkzjbHD2K8ug087puJ.png",
    },
  },
  {
    body: "Permanece o problema",
    date: "2024-04-29T13:44:35.000Z",
    caption: null,
    type: "chat",
    sent: false,
    user: null,
  },
  {
    body: "Nao esta funcionando",
    date: "2024-04-29T13:44:26.000Z",
    caption: null,
    type: "chat",
    sent: false,
    user: null,
  },
  {
    body: "🙎‍♂️ *Michael Mascarenhas:*\nEi, Bom dia!\n\nTivemos uma breve indisponibilidade, porém, acabou de ser resolvido. \n\npoderia verificar se está OK para vocês?",
    date: "2024-04-29T13:17:34.000Z",
    caption: null,
    type: "chat",
    sent: true,
    user: {
      nome: "Michael Mascarenhas",
      id_user: 5031,
      foto_perfil: "l18NKYEZl0K6PF04RzngsVLUKvxxgAS4QkzjbHD2K8ug087puJ.png",
    },
  },
  {
    body: "As mensagens não estão indo",
    date: "2024-04-29T12:32:07.000Z",
    caption: null,
    type: "chat",
    sent: false,
    user: null,
  },
  {
    body: "Chat caiu de novo",
    date: "2024-04-29T12:31:53.000Z",
    caption: null,
    type: "chat",
    sent: false,
    user: null,
  },
  {
    body: "Ola",
    date: "2024-04-29T12:31:48.000Z",
    caption: null,
    type: "chat",
    sent: false,
    user: null,
  },
  {
    body: "E os atendimentos daqueles clientes que citei ainda não corrigiu",
    date: "2024-04-22T16:20:36.000Z",
    caption: null,
    type: "chat",
    sent: false,
    user: null,
  },
  {
    body: "Parou de sair a descrição",
    date: "2024-04-22T16:20:05.000Z",
    caption: null,
    type: "chat",
    sent: false,
    user: null,
  },
  {
    body: "Ainda não resolveu",
    date: "2024-04-22T16:19:56.000Z",
    caption: null,
    type: "chat",
    sent: false,
    user: null,
  },
  {
    body: "Aguardo",
    date: "2024-04-22T11:50:57.000Z",
    caption: null,
    type: "chat",
    sent: false,
    user: null,
  },
  {
    body: "Ei Francielli, já vou verificar o que aconteceu, só um momento por favor.",
    date: "2024-04-22T11:50:06.000Z",
    caption: null,
    type: "chat",
    sent: true,
    user: {
      nome: "Michael Mascarenhas",
      id_user: 5031,
      foto_perfil: "l18NKYEZl0K6PF04RzngsVLUKvxxgAS4QkzjbHD2K8ug087puJ.png",
    },
  },
];

export const CALLED_EXEMPLO_1: Called = {
  id_chamado: 1,
};

export const CALLED_EXEMPLO_2: Called = {
  id_chamado: 2,
};
